<template>
    <i class="icon iconfont" :class="iconType"></i>
</template>

<script>
    export default {
        props: ['type'],
        data() {
            return {
                iconType: {
                    'icon-all': this.type === 'all',
                    'icon-back': this.type === 'back',
                    'icon-cart': this.type === 'cart',
                    'icon-category': this.type === 'category',
                    'icon-close': this.type === 'close',
                    'icon-comments': this.type === 'comments',
                    'icon-cry': this.type === 'cry',
                    'icon-delete': this.type === 'delete',
                    'icon-edit': this.type === 'edit',
                    'icon-email': this.type === 'email',
                    'icon-favorite': this.type === 'favorite',
                    'icon-from': this.type === 'from',
                    'icon-help': this.type === 'help',
                    'icon-information': this.type === 'information',
                    'icon-less': this.type === 'less',
                    'icon-moreunfold': this.type === 'more_unfold',
                    'icon-more': this.type === 'more',
                    'icon-pic': this.type === 'pic',
                    'icon-qrcode': this.type === 'QRCode',
                    'icon-refresh': this.type === 'refresh',
                    'icon-rfq': this.type === 'RFQ',
                    'icon-search': this.type === 'search',
                    'icon-selected': this.type === 'selected',
                    'icon-set': this.type === 'set',
                    'icon-smile': this.type === 'smile',
                    'icon-success': this.type === 'success',
                    'icon-survey': this.type === 'survey',
                    'icon-viewgallery': this.type === 'ViewGallery',
                    'icon-viewlist': this.type === 'Viewlist',
                    'icon-warning': this.type === 'warning',
                    'icon-wrong': this.type === 'wrong',
                    'icon-account': this.type === 'account',
                    'icon-add': this.type === 'add',
                    'icon-clock': this.type === 'clock',
                    'icon-remind': this.type === 'remind',
                    'icon-calendar': this.type === 'calendar',
                    'icon-attachment': this.type === 'attachment',
                    'icon-discount': this.type === 'discount',
                    'icon-service': this.type === 'service',
                    'icon-print': this.type === 'print',
                    'icon-box': this.type === 'box',
                    'icon-process': this.type === 'process',
                    'icon-beauty': this.type === 'beauty',
                    'icon-electrical': this.type === 'electrical',
                    'icon-home': this.type === 'home',
                    'icon-electronics': this.type === 'electronics',
                    'icon-gifts': this.type === 'gifts',
                    'icon-lights': this.type === 'lights',
                    'icon-sports': this.type === 'sports',
                    'icon-auto': this.type === 'auto',
                    'icon-jewelry': this.type === 'jewelry',
                    'icon-browse': this.type === 'browse',
                    'icon-rfqqm': this.type === 'rfq-qm',
                    'icon-rfqquantity': this.type === 'rfq-quantity',
                    'icon-rfq1': this.type === 'rfq1',
                    'icon-scanning': this.type === 'scanning',
                    'icon-compare': this.type === 'compare',
                    'icon-filter': this.type === 'filter',
                    'icon-pin': this.type === 'pin',
                    'icon-history': this.type === 'history',
                    'icon-productfeatures': this.type === 'product-features',
                    'icon-supplierfeatures': this.type === 'supplier-features',
                    'icon-similarproduct': this.type === 'similar-product',
                    'icon-link': this.type === 'link',
                    'icon-cut': this.type === 'cut',
                    'icon-navlist': this.type === 'nav-list',
                    'icon-imagetext': this.type === 'image-text',
                    'icon-text': this.type === 'text',
                    'icon-move': this.type === 'move',
                    'icon-subtract': this.type === 'subtract',
                    'icon-dollar': this.type === 'dollar',
                    'icon-raw': this.type === 'raw',
                    'icon-office': this.type === 'office',
                    'icon-agriculture': this.type === 'agriculture',
                    'icon-machinery': this.type === 'machinery',
                    'icon-assessedbadge': this.type === 'assessed-Badge',
                    'icon-gerenzhongxin': this.type === 'personal-center',
                    'icon-integral': this.type === 'integral',
                    'icon-operation': this.type === 'operation',
                    'icon-remind': this.type === 'remind',
                    'icon-download': this.type === 'download',
                    'icon-map': this.type === 'map',
                    'icon-bad': this.type === 'bad',
                    'icon-good': this.type === 'good',
                    'icon-skip': this.type === 'skip',
                    'icon-iconfontplay2': this.type === 'play',
                    'icon-iconfontstop': this.type === 'stop',
                    'icon-compass': this.type === 'compass',
                    'icon-security': this.type === 'security',
                    'icon-share': this.type === 'share',
                    'icon-store': this.type === 'store',
                    'icon-phone': this.type === 'phone',
                    'icon-bussinessman': this.type === 'bussiness-man',
                    'icon-shoes': this.type === 'shoes',
                    'icon-mobilephone': this.type === 'Mobile-phone',
                    'icon-emailfilling': this.type === 'email-filling',
                    'icon-favoritesfilling': this.type === 'favorites-filling',
                    'icon-accountfilling': this.type === 'account-filling',
                    'icon-creditlevel': this.type === 'credit-level',
                    'icon-creditlevelfilling': this.type === 'credit-level-filling',
                    'icon-exl': this.type === 'exl',
                    'icon-pdf': this.type === 'pdf',
                    'icon-zip': this.type === 'zip',
                    'icon-sorting': this.type === 'sorting',
                    'icon-copy': this.type === 'copy',
                    'icon-save': this.type === 'save',
                    'icon-inquirytemplate': this.type === 'inquiry-template',
                    'icon-templatedefault': this.type === 'template-default',
                    'icon-libra': this.type === 'libra',
                    'icon-survey': this.type === 'survey',
                    'icon-ship': this.type === 'ship',
                    'icon-bussinesscard': this.type === 'bussiness-card',
                    'icon-hot': this.type === 'hot',
                    'icon-data': this.type === 'data',
                    'icon-trade': this.type === 'trade',
                    'icon-onepage48': this.type === 'onepage',
                    'icon-signboard': this.type === 'signboard',
                    'icon-shuffling-banner': this.type === 'shuffling-banner',
                    'icon-component': this.type === 'component',
                    'icon-componentfilling': this.type === 'component-filling',
                    'icon-color': this.type === 'color',
                    'icon-color-filling': this.type === 'color-filling',
                    'icon-favorites': this.type === 'favorites',
                    'icon-pic-filling': this.type === 'pic-filling',
                    'icon-RFQ-filling': this.type === 'RFQ-filling',
                    'icon-originalimage': this.type === 'original-image',
                    'icon-Calculator': this.type === 'Calculator',
                    'icon-video': this.type === 'video',
                    'icon-earth': this.type === 'earth',
                    'icon-task-management': this.type === 'task-management',
                    'icon-trust': this.type === 'trust',
                    'icon-password': this.type === 'password',
                    'icon-column': this.type === '3column',
                    'icon-apparel': this.type === 'apparel',
                    'icon-bags': this.type === 'bags',
                    'icon-folder': this.type === 'folder',
                    'icon-column1': this.type === '4column',
                    'icon-code': this.type === 'code',
                    'icon-customs-clearance': this.type === 'customs-clearance',
                    'icon-good-filling': this.type === 'good-filling',
                    'icon-camera': this.type === 'camera'
                }
            }
        }
    }
</script>

<style scoped lang="scss">
    @import url('./font_icon/iconfont.css');
    .t-icon {
        vertical-align: middle;
        font-size: inherit;
        font-weight: inherit;
    }
</style>
